#include <stdio.h>
#include <conio.h>
#include <math.h>
main(){
float A,T,SM,LS,E;
printf("\tAri Ramadhani");
printf("\n\t2016230037\n\n");
printf("\tMENGHITUNG SEGITIGA");
printf("\nAlas\t\t  = ");
scanf("%f",&A);
printf("Tinggi\t\t  = ");
scanf("%f",&T);
printf("Sisi miring\t  = %f",SM=sqrt(A*A+T*T),&SM);
printf("\nLuas segitiga\t  = %f",(A*T)/2,&LS);
printf("\nKeliling segitiga =%f",A+T+SM),&E;
getch();
}

